# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import ast
import json
import logging
import os
from abc import ABC, abstractmethod
from typing import Any, Optional

import regex
from pydantic import BaseModel

from verl.tools.schemas import OpenAIFunctionToolSchema
from verl.utils.ray_utils import get_event_loop
from verl.utils.rollout_trace import rollout_trace_op

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))

TOOL_PARSER_ERROR_FUNCTION_NAME = "__tool_parser_error__"


class FunctionCall(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""

    internal: bool = False
    """Whether this call was generated internally by the parser rather than the model."""


def _build_tool_parser_error_call(message: str) -> FunctionCall:
    return FunctionCall(
        name=TOOL_PARSER_ERROR_FUNCTION_NAME,
        arguments=json.dumps({"message": message}, ensure_ascii=False),
        internal=True,
    )


def _tool_parser_error(message: str) -> list[FunctionCall]:
    logger.warning(message)
    return [_build_tool_parser_error_call(message)]


class ToolParser(ABC):
    _registry: dict[str, type["ToolParser"]] = {}

    def __init__(self, tokenizer) -> None:
        self.tokenizer = tokenizer

    @abstractmethod
    async def extract_tool_calls(
        self, responses_ids: list[int], tools: list[OpenAIFunctionToolSchema] = None
    ) -> tuple[str, list[FunctionCall]]:
        """Extract tool calls from the responses.

        Args:
            responses_ids (List[int]): The ids of the responses.
            tools (List[OpenAIFunctionToolSchema], optional): OpenAI function tool schema.

        Returns:
            Tuple[str, List[FunctionCall]]: Content and extracted tool calls.
        """
        raise NotImplementedError

    @classmethod
    def get_tool_parser(cls, name: str, tokenizer):
        if name not in cls._registry:
            raise ValueError(f"Unknown tool parser: {name}")
        return cls._registry[name](tokenizer)

    @classmethod
    def register(cls, name: str):
        def decorator(subclass: type[ToolParser]) -> type[ToolParser]:
            cls._registry[name] = subclass
            return subclass

        return decorator


@ToolParser.register("hermes")
class HermesToolParser(ToolParser):
    """Adapted from https://github.com/vllm-project/vllm/blob/v0.9.1/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py"""

    def __init__(self, tokenizer) -> None:
        super().__init__(tokenizer)

        self.tool_call_start_token: str = "<tool_call>"
        self.tool_call_end_token: str = "</tool_call>"
        self.tool_call_regex = regex.compile(r"<tool_call>(.*?)</tool_call>", regex.DOTALL)

    @rollout_trace_op
    async def extract_tool_calls(
        self, responses_ids: list[int], tools: list[OpenAIFunctionToolSchema] = None
    ) -> tuple[str, list[FunctionCall]]:
        loop = get_event_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)
        think_end = text.rfind("</think>")
        reasoning_region = text[: think_end + len("</think>")] if think_end >= 0 else ""
        parse_region = text[think_end + len("</think>") :] if think_end >= 0 else text
        parse_region_label = " after </think>" if think_end >= 0 else ""

        if self.tool_call_start_token in reasoning_region:
            return text, _tool_parser_error(
                "Tool call parse error: found '<tool_call>' inside reasoning content before the final "
                "'</think>'. Put tool calls after '</think>'."
            )

        if self.tool_call_start_token not in parse_region:
            return text, []

        if self.tool_call_end_token not in parse_region:
            return text, _tool_parser_error(
                "Tool call parse error: found '<tool_call>' but missing '</tool_call>'. Close the tool call block."
            )

        matches = self.tool_call_regex.findall(parse_region)
        if not matches:
            return text, _tool_parser_error(
                f"Tool call parse error: could not find a complete '<tool_call>...</tool_call>' block"
                f"{parse_region_label}."
            )

        function_calls = []
        errors: list[str] = []
        for match in matches:
            try:
                function_call = json.loads(match)
                name, arguments = function_call["name"], function_call["arguments"]
                function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))
            except Exception as e:
                errors.append(str(e))
                logger.error(f"Failed to decode tool call: {e}")

        # remaing text exclude tool call tokens
        content = self.tool_call_regex.sub("", text)

        if errors:
            error_str = errors[0] if errors else "invalid tool call"
            return content, _tool_parser_error(
                "Tool call parse error: invalid JSON inside '<tool_call>...</tool_call>'. "
                f"Parser error: {error_str}. Use JSON with keys 'name' and 'arguments'."
            )

        return content, function_calls


@ToolParser.register("gpt-oss")
class GptOssToolParser(ToolParser):
    """
    Tool parser for gpt-oss model.
    Adapted from https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/function_call/gpt_oss_detector.py

    Args:
        tokenizer: The tokenizer to use.
    """

    def __init__(self, tokenizer) -> None:
        super().__init__(tokenizer)
        # check https://cookbook.openai.com/articles/openai-harmony for more details.
        self.cot_pattern = regex.compile(
            r"<\|start\|>assistant<\|channel\|>analysis<\|message\|>.*?<\|end\|>", regex.DOTALL
        )
        # <|start|>assistant may be pre-appended in prompts, so we need to remove it.
        self.partial_cot_pattern = regex.compile(r"<\|channel\|>analysis<\|message\|>(.*?)<\|end\|>", regex.DOTALL)
        self.tool_call_pattern = regex.compile(
            r"<\|start\|>assistant<\|channel\|>[^<]* to=functions\.([^<]+) "
            r"<\|constrain\|>json<\|message\|>(.*?)<\|call\|>",
            regex.DOTALL,
        )

    @rollout_trace_op
    async def extract_tool_calls(
        self, responses_ids: list[int], tools: list[OpenAIFunctionToolSchema] = None
    ) -> tuple[str, list[FunctionCall]]:
        loop = get_event_loop()
        # We need to keep special tokens for gpt-oss model for better tool call extraction.
        text = await loop.run_in_executor(None, lambda: self.tokenizer.decode(responses_ids, skip_special_tokens=False))
        # Need to remove padding tokens for better tool call extraction.
        text = text.replace(self.tokenizer.pad_token, "")
        # Need to reomve COT since COT may contain tool call tokens.But they are not valid tool calls.
        text = regex.sub(self.cot_pattern, "", text)
        text = regex.sub(self.partial_cot_pattern, "", text)

        # check if there are tool calls in the text by re.findall
        matches = regex.findall(self.tool_call_pattern, text)
        if not matches:
            return text, []

        function_calls = []
        for match in matches:
            try:
                name, arguments = match[0], match[1]
                # don't check if arguments is valid JSON and leave it to client
                function_calls.append(FunctionCall(name=name, arguments=arguments))
            except Exception as e:
                logger.error(f"Failed to decode tool call: {e}")

        # remaing text exclude tool call tokens
        content = regex.sub(self.tool_call_pattern, "", text)

        return content, function_calls


@ToolParser.register("qwen3_coder")
class Qwen3XMLToolParser(ToolParser):
    """
    Tool parser for qwen3_coder/qwen3.5 model.
    Adapted from https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct/blob/main/qwen3coder_tool_parser.py

    Args:
        tokenizer: The tokenizer to use.
    """

    def __init__(self, tokenizer):
        super().__init__(tokenizer)

        self.tool_call_start_token: str = "<tool_call>"
        self.tool_call_end_token: str = "</tool_call>"
        self.tool_call_prefix: str = "<function="

        self.tool_call_function_start_regex = regex.compile(r"<function=([^>\r\n]+)>")
        self.tool_call_parameter_start_regex = regex.compile(r"<parameter=([^>\r\n]+)>")

    def _parse_xml_function_call(
        self, function_name: str, parameters: list[tuple[str, str]], tools: Optional[list[OpenAIFunctionToolSchema]]
    ) -> FunctionCall:
        def get_arguments_config(func_name: str) -> dict:
            for config in tools or []:
                if config.type == "function" and config.function.name == func_name:
                    properties = config.function.parameters.properties
                    return {k: v.model_dump() for k, v in properties.items()}
            logger.warning(f"Tool '{func_name}' is not defined in the tools list.")
            return {}

        def convert_param_value(param_value: str, param_name: str, param_config: dict, func_name: str) -> Any:
            def parse_structured_with_fallback(raw_value: str, expected_type: type, expected_name: str) -> Any:
                parsed_value: Any = None
                try:
                    parsed_value = json.loads(raw_value)
                except Exception:
                    try:
                        parsed_value = ast.literal_eval(raw_value)
                    except Exception:
                        logger.warning(
                            f"Parsed value '{raw_value}' of parameter '{param_name}' is not a valid "
                            f"{expected_name} literal in tool '{func_name}', degenerating to string."
                        )
                        return raw_value
                if not isinstance(parsed_value, expected_type):
                    logger.warning(
                        f"Parsed value '{raw_value}' of parameter '{param_name}' in tool '{func_name}' "
                        f"is not a {expected_name}, degenerating to string."
                    )
                    return raw_value
                return parsed_value

            def parse_json_scalar_with_fallback(raw_value: str) -> Any:
                try:
                    return json.loads(raw_value)
                except Exception:
                    try:
                        parsed_value = ast.literal_eval(raw_value)
                    except Exception:
                        logger.warning(
                            f"Parsed value '{raw_value}' of parameter '{param_name}' cannot be converted "
                            f"via safe literal parser for tool '{func_name}', degenerating to string."
                        )
                        return raw_value
                    if isinstance(parsed_value, (dict, list, str, int, float, bool)) or parsed_value is None:
                        return parsed_value
                    return raw_value

            # Handle null value for any type
            if param_value.lower() == "null":
                return None

            if param_name not in param_config:
                if param_config != {}:
                    logger.warning(
                        f"Parsed parameter '{param_name}' is not defined in the tool "
                        f"parameters for tool '{func_name}', directly returning the string value."
                    )
                return param_value

            if isinstance(param_config[param_name], dict) and "type" in param_config[param_name]:
                param_type = str(param_config[param_name]["type"]).strip().lower()
            else:
                param_type = "string"
            if param_type in ["string", "str", "text", "varchar", "char", "enum"]:
                return param_value
            elif (
                param_type.startswith("int")
                or param_type.startswith("uint")
                or param_type.startswith("long")
                or param_type.startswith("short")
                or param_type.startswith("unsigned")
            ):
                try:
                    param_value = int(param_value)
                except Exception:
                    logger.warning(
                        f"Parsed value '{param_value}' of parameter '{param_name}' is not an integer in tool "
                        f"'{func_name}', degenerating to string."
                    )
                return param_value
            elif param_type.startswith("num") or param_type.startswith("float"):
                try:
                    float_param_value = float(param_value)
                    param_value = (
                        float_param_value if float_param_value - int(float_param_value) != 0 else int(float_param_value)
                    )
                except Exception:
                    logger.warning(
                        f"Parsed value '{param_value}' of parameter '{param_name}' is not a float in tool "
                        f"'{func_name}', degenerating to string."
                    )
                return param_value
            elif param_type in ["boolean", "bool", "binary"]:
                param_value = param_value.lower()
                if param_value not in ["true", "false"]:
                    logger.warning(
                        f"Parsed value '{param_value}' of parameter '{param_name}' is not a "
                        f"boolean (`true` of `false`) in tool '{func_name}', degenerating to false."
                    )
                return param_value == "true"
            else:
                if param_type == "object" or param_type.startswith("dict"):
                    return parse_structured_with_fallback(param_value, dict, "object")
                if param_type == "array" or param_type.startswith("list"):
                    return parse_structured_with_fallback(param_value, list, "array")
                return parse_json_scalar_with_fallback(param_value)

        function_name = function_name.strip()
        if not function_name or not regex.fullmatch(r"[A-Za-z0-9_.-]+", function_name):
            raise ValueError(f"invalid function name in XML tool call: {function_name!r}")
        param_config = get_arguments_config(function_name)
        param_dict = {}
        for param_name, param_value in parameters:
            param_name = param_name.strip()
            if not param_name:
                raise ValueError(f"invalid parameter name in XML tool call: {param_name!r}")
            param_value = str(param_value)
            # Remove prefix and trailing \n
            if param_value.startswith("\n"):
                param_value = param_value[1:]
            if param_value.endswith("\n"):
                param_value = param_value[:-1]

            param_dict[param_name] = convert_param_value(param_value, param_name, param_config, function_name)
        return FunctionCall(name=function_name, arguments=json.dumps(param_dict, ensure_ascii=False))

    def _skip_xml_whitespace(self, text: str, pos: int) -> int:
        while pos < len(text) and text[pos].isspace():
            pos += 1
        return pos

    def _get_function_calls(self, model_output: str) -> tuple[list[tuple[str, list[tuple[str, str]]]], Optional[str]]:
        function_calls = []
        search_pos = 0

        while True:
            tool_call_start = model_output.find(self.tool_call_start_token, search_pos)
            if tool_call_start < 0:
                return function_calls, None

            pos = tool_call_start + len(self.tool_call_start_token)
            found_function = False
            while True:
                pos = self._skip_xml_whitespace(model_output, pos)
                if model_output.startswith(self.tool_call_end_token, pos):
                    if not found_function:
                        return [], (
                            "Tool call parse error: could not parse a '<function=...>...</function>' block inside "
                            "'<tool_call>'. Use XML like: <tool_call><function=tool_name>"
                            "<parameter=name>value</parameter></function></tool_call>."
                        )
                    search_pos = pos + len(self.tool_call_end_token)
                    break
                if pos >= len(model_output):
                    return [], "Tool call parse error: unbalanced XML tool call tags (missing '</tool_call>')."

                function_match = self.tool_call_function_start_regex.match(model_output, pos)
                if function_match is None:
                    if model_output.startswith(self.tool_call_prefix, pos):
                        return [], (
                            "Tool call parse error: could not parse a '<function=...>...</function>' block inside "
                            "'<tool_call>'. Use XML like: <tool_call><function=tool_name>"
                            "<parameter=name>value</parameter></function></tool_call>."
                        )
                    return [], (
                        "Tool call parse error: invalid XML tool call content inside '<tool_call>...</tool_call>'. "
                        "Expected '<function=...>' or '</tool_call>'."
                    )

                function_name = function_match.group(1).strip()
                pos = function_match.end()
                found_function = True
                parameters = []

                while True:
                    pos = self._skip_xml_whitespace(model_output, pos)
                    if model_output.startswith("</function>", pos):
                        pos += len("</function>")
                        function_calls.append((function_name, parameters))
                        break
                    if pos >= len(model_output) or model_output.startswith(self.tool_call_end_token, pos):
                        return [], (
                            "Tool call parse error: unbalanced XML function tags inside '<tool_call>...</tool_call>' "
                            "(missing '</function>')."
                        )

                    parameter_match = self.tool_call_parameter_start_regex.match(model_output, pos)
                    if parameter_match is None:
                        if model_output.startswith("<parameter=", pos):
                            return [], (
                                "Tool call parse error: invalid XML parameter tag inside '<function=...>...</function>'. "
                                "Use '<parameter=name>value</parameter>'."
                            )
                        return [], (
                            "Tool call parse error: invalid XML function content inside '<function=...>...</function>'. "
                            "Expected '<parameter=...>' or '</function>'."
                        )

                    parameter_name = parameter_match.group(1).strip()
                    value_start = parameter_match.end()
                    value_end = model_output.find("</parameter>", value_start)
                    if value_end < 0:
                        return [], (
                            "Tool call parse error: unbalanced XML parameter tags inside '<function=...>...</function>' "
                            "(missing '</parameter>')."
                        )

                    parameters.append((parameter_name, model_output[value_start:value_end]))
                    pos = value_end + len("</parameter>")

    @rollout_trace_op
    async def extract_tool_calls(
        self, responses_ids: list[int], tools: list[OpenAIFunctionToolSchema] = None
    ) -> tuple[str, list[FunctionCall]]:
        loop = get_event_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)
        if self.tool_call_start_token not in text:
            return text, []

        try:
            function_calls, parser_error = self._get_function_calls(text)
            if parser_error is not None:
                return text, _tool_parser_error(parser_error)
            if len(function_calls) == 0:
                return text, _tool_parser_error(
                    "Tool call parse error: could not parse a '<function=...>...</function>' block inside "
                    "'<tool_call>'. Use XML like: <tool_call><function=tool_name>"
                    "<parameter=name>value</parameter></function></tool_call>."
                )

            tool_calls = [
                self._parse_xml_function_call(function_name, parameters, tools)
                for function_name, parameters in function_calls
            ]

            # Extract content before tool calls
            content_index = text.find(self.tool_call_start_token)
            content_index = content_index if content_index >= 0 else text.find(self.tool_call_prefix)
            content = text[:content_index]  # .rstrip()

            return content, tool_calls
        except Exception as e:
            logger.exception(f"Error in extracting tool call from response: {e}")
            return text, _tool_parser_error(
                "Tool call parse error: invalid XML tool call format inside '<tool_call>...</tool_call>'. "
                f"Parser error: {e}"
            )
